services:
  - type: web
    name: jee-predictor-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
